export const CONFIG = {
  SIM_RIGS: {
    '1': {
      eventQueue: 'simrig1_event',
      motionQueue: 'simrig1_motion',
      carsetupsQueue: 'simrig1_carsetups',
      lapdataQueue: 'simrig1_lapdata',
      sessionQueue: 'simrig1_session',
      participantsQueue: 'simrig1_participants',
      cartelemetryQueue: 'simrig1_cartelemetry',
      carstatusQueue: 'simrig1_carstatus',
      finalclassificationQueue: 'simrig1_finalclassification',
      lobbyinfoQueue: 'simrig1_lobbyinfo',
      cardamageQueue: 'simrig1_cardamage',
      sessionhistoryQueue: 'simrig1_sessionhistory',
      tyresetsQueue: 'simrig1_tyresets',
      motionexQueue: 'simrig1_motionex',
    },
    '2': {
      eventQueue: 'simrig2_event',
      motionQueue: 'simrig2_motion',
      carsetupsQueue: 'simrig2_carsetups',
      lapdataQueue: 'simrig2_lapdata',
      sessionQueue: 'simrig2_session',
      participantsQueue: 'simrig2_participants',
      cartelemetryQueue: 'simrig2_cartelemetry',
      carstatusQueue: 'simrig2_carstatus',
      finalclassificationQueue: 'simrig2_finalclassification',
      lobbyinfoQueue: 'simrig2_lobbyinfo',
      cardamageQueue: 'simrig2_cardamage',
      sessionhistoryQueue: 'simrig2_sessionhistory',
      tyresetsQueue: 'simrig2_tyresets',
      motionexQueue: 'simrig2_motionex',
    },
    '3': {
      eventQueue: 'simrig3_event',
      motionQueue: 'simrig3_motion',
      carsetupsQueue: 'simrig3_carsetups',
      lapdataQueue: 'simrig3_lapdata',
      sessionQueue: 'simrig3_session',
      participantsQueue: 'simrig3_participants',
      cartelemetryQueue: 'simrig3_cartelemetry',
      carstatusQueue: 'simrig3_carstatus',
      finalclassificationQueue: 'simrig3_finalclassification',
      lobbyinfoQueue: 'simrig3_lobbyinfo',
      cardamageQueue: 'simrig3_cardamage',
      sessionhistoryQueue: 'simrig3_sessionhistory',
      tyresetsQueue: 'simrig3_tyresets',
      motionexQueue: 'simrig3_motionex',
    },

  }
};
